SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_PLUGIN_FIELDS (
    P_TIPO_OBJETO VARCHAR(20),
    P_OBJETO VARCHAR(63)
)
RETURNS (
    ID_TMPFLD01 INTEGER,
    TMPFLD01_TIPO_OBJETO VARCHAR(20),
    TMPFLD01_OBJETO VARCHAR(63),
    TMPFLD01_SECCION VARCHAR(20),
    TMPFLD01_CAMPO VARCHAR(63),
    TMPFLD01_POSICION INTEGER,
    TMPFLD01_TIPO_DATO VARCHAR(80),
    TMPFLD01_LONGITUD INTEGER,
    TMPFLD01_ESCALA INTEGER,
    TMPFLD01_PRECISION INTEGER,
    TMPFLD01_REQUERIDO VARCHAR(1),
    TMPFLD01_FAPL TIMESTAMP
)
AS
DECLARE VARIABLE V_TIPO_OBJETO VARCHAR(20);
DECLARE VARIABLE V_OBJETO VARCHAR(63);
DECLARE VARIABLE V_FIELD_TYPE SMALLINT;
DECLARE VARIABLE V_FIELD_SUB_TYPE SMALLINT;
DECLARE VARIABLE V_FIELD_LENGTH SMALLINT;
DECLARE VARIABLE V_FIELD_SCALE SMALLINT;
DECLARE VARIABLE V_FIELD_PRECISION SMALLINT;
DECLARE VARIABLE V_NULL_FLAG SMALLINT;
BEGIN
  ID_TMPFLD01 = 0;
  V_TIPO_OBJETO = UPPER(TRIM(:P_TIPO_OBJETO));
  V_OBJETO = UPPER(TRIM(:P_OBJETO));

  IF ((V_TIPO_OBJETO = 'TABLE') OR (V_TIPO_OBJETO = 'VIEW')) THEN
  BEGIN
    FOR
      SELECT
          TRIM(RF.RDB$FIELD_NAME),
          RF.RDB$FIELD_POSITION,
          F.RDB$FIELD_TYPE,
          COALESCE(F.RDB$FIELD_SUB_TYPE, 0),
          COALESCE(F.RDB$FIELD_LENGTH, 0),
          COALESCE(F.RDB$FIELD_SCALE, 0),
          COALESCE(F.RDB$FIELD_PRECISION, 0),
          COALESCE(RF.RDB$NULL_FLAG, F.RDB$NULL_FLAG)
      FROM RDB$RELATION_FIELDS RF
      JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE
      JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME
      WHERE RF.RDB$RELATION_NAME = :V_OBJETO
        AND COALESCE(R.RDB$SYSTEM_FLAG, 0) = 0
      ORDER BY RF.RDB$FIELD_POSITION
      INTO
          :TMPFLD01_CAMPO,
          :TMPFLD01_POSICION,
          :V_FIELD_TYPE,
          :V_FIELD_SUB_TYPE,
          :V_FIELD_LENGTH,
          :V_FIELD_SCALE,
          :V_FIELD_PRECISION,
          :V_NULL_FLAG
    DO
    BEGIN
      ID_TMPFLD01 = ID_TMPFLD01 + 1;
      TMPFLD01_TIPO_OBJETO = V_TIPO_OBJETO;
      TMPFLD01_OBJETO = V_OBJETO;
      TMPFLD01_SECCION = 'CAMPO';
      TMPFLD01_TIPO_DATO = 'UNKNOWN';
      TMPFLD01_LONGITUD = V_FIELD_LENGTH;
      TMPFLD01_ESCALA = V_FIELD_SCALE;
      TMPFLD01_PRECISION = V_FIELD_PRECISION;
      TMPFLD01_REQUERIDO = IIF(V_NULL_FLAG = 1, 'S', 'N');
      TMPFLD01_FAPL = CURRENT_TIMESTAMP;

      IF (V_FIELD_TYPE = 7) THEN TMPFLD01_TIPO_DATO = IIF(V_FIELD_SUB_TYPE = 1, 'NUMERIC', IIF(V_FIELD_SUB_TYPE = 2, 'DECIMAL', 'SMALLINT'));
      IF (V_FIELD_TYPE = 8) THEN TMPFLD01_TIPO_DATO = IIF(V_FIELD_SUB_TYPE = 1, 'NUMERIC', IIF(V_FIELD_SUB_TYPE = 2, 'DECIMAL', 'INTEGER'));
      IF (V_FIELD_TYPE = 10) THEN TMPFLD01_TIPO_DATO = 'FLOAT';
      IF (V_FIELD_TYPE = 12) THEN TMPFLD01_TIPO_DATO = 'DATE';
      IF (V_FIELD_TYPE = 13) THEN TMPFLD01_TIPO_DATO = 'TIME';
      IF (V_FIELD_TYPE = 14) THEN TMPFLD01_TIPO_DATO = 'CHAR';
      IF (V_FIELD_TYPE = 16) THEN TMPFLD01_TIPO_DATO = IIF(V_FIELD_SUB_TYPE = 1, 'NUMERIC', IIF(V_FIELD_SUB_TYPE = 2, 'DECIMAL', 'BIGINT'));
      IF (V_FIELD_TYPE = 27) THEN TMPFLD01_TIPO_DATO = 'DOUBLE PRECISION';
      IF (V_FIELD_TYPE = 35) THEN TMPFLD01_TIPO_DATO = 'TIMESTAMP';
      IF (V_FIELD_TYPE = 37) THEN TMPFLD01_TIPO_DATO = 'VARCHAR';
      IF (V_FIELD_TYPE = 261) THEN TMPFLD01_TIPO_DATO = 'BLOB';

      SUSPEND;
    END
  END

  IF (V_TIPO_OBJETO = 'PROCEDURE') THEN
  BEGIN
    FOR
      SELECT
          TRIM(P.RDB$PARAMETER_NAME),
          P.RDB$PARAMETER_NUMBER,
          F.RDB$FIELD_TYPE,
          COALESCE(F.RDB$FIELD_SUB_TYPE, 0),
          COALESCE(F.RDB$FIELD_LENGTH, 0),
          COALESCE(F.RDB$FIELD_SCALE, 0),
          COALESCE(F.RDB$FIELD_PRECISION, 0),
          COALESCE(P.RDB$NULL_FLAG, F.RDB$NULL_FLAG)
      FROM RDB$PROCEDURE_PARAMETERS P
      JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = P.RDB$FIELD_SOURCE
      WHERE P.RDB$PROCEDURE_NAME = :V_OBJETO
        AND P.RDB$PARAMETER_TYPE = 0
      ORDER BY P.RDB$PARAMETER_NUMBER
      INTO
          :TMPFLD01_CAMPO,
          :TMPFLD01_POSICION,
          :V_FIELD_TYPE,
          :V_FIELD_SUB_TYPE,
          :V_FIELD_LENGTH,
          :V_FIELD_SCALE,
          :V_FIELD_PRECISION,
          :V_NULL_FLAG
    DO
    BEGIN
      ID_TMPFLD01 = ID_TMPFLD01 + 1;
      TMPFLD01_TIPO_OBJETO = V_TIPO_OBJETO;
      TMPFLD01_OBJETO = V_OBJETO;
      TMPFLD01_SECCION = 'PARAMETRO';
      TMPFLD01_TIPO_DATO = 'UNKNOWN';
      TMPFLD01_LONGITUD = V_FIELD_LENGTH;
      TMPFLD01_ESCALA = V_FIELD_SCALE;
      TMPFLD01_PRECISION = V_FIELD_PRECISION;
      TMPFLD01_REQUERIDO = IIF(V_NULL_FLAG = 1, 'S', 'N');
      TMPFLD01_FAPL = CURRENT_TIMESTAMP;

      IF (V_FIELD_TYPE = 7) THEN TMPFLD01_TIPO_DATO = IIF(V_FIELD_SUB_TYPE = 1, 'NUMERIC', IIF(V_FIELD_SUB_TYPE = 2, 'DECIMAL', 'SMALLINT'));
      IF (V_FIELD_TYPE = 8) THEN TMPFLD01_TIPO_DATO = IIF(V_FIELD_SUB_TYPE = 1, 'NUMERIC', IIF(V_FIELD_SUB_TYPE = 2, 'DECIMAL', 'INTEGER'));
      IF (V_FIELD_TYPE = 10) THEN TMPFLD01_TIPO_DATO = 'FLOAT';
      IF (V_FIELD_TYPE = 12) THEN TMPFLD01_TIPO_DATO = 'DATE';
      IF (V_FIELD_TYPE = 13) THEN TMPFLD01_TIPO_DATO = 'TIME';
      IF (V_FIELD_TYPE = 14) THEN TMPFLD01_TIPO_DATO = 'CHAR';
      IF (V_FIELD_TYPE = 16) THEN TMPFLD01_TIPO_DATO = IIF(V_FIELD_SUB_TYPE = 1, 'NUMERIC', IIF(V_FIELD_SUB_TYPE = 2, 'DECIMAL', 'BIGINT'));
      IF (V_FIELD_TYPE = 27) THEN TMPFLD01_TIPO_DATO = 'DOUBLE PRECISION';
      IF (V_FIELD_TYPE = 35) THEN TMPFLD01_TIPO_DATO = 'TIMESTAMP';
      IF (V_FIELD_TYPE = 37) THEN TMPFLD01_TIPO_DATO = 'VARCHAR';
      IF (V_FIELD_TYPE = 261) THEN TMPFLD01_TIPO_DATO = 'BLOB';

      SUSPEND;
    END

    FOR
      SELECT
          TRIM(P.RDB$PARAMETER_NAME),
          P.RDB$PARAMETER_NUMBER,
          F.RDB$FIELD_TYPE,
          COALESCE(F.RDB$FIELD_SUB_TYPE, 0),
          COALESCE(F.RDB$FIELD_LENGTH, 0),
          COALESCE(F.RDB$FIELD_SCALE, 0),
          COALESCE(F.RDB$FIELD_PRECISION, 0),
          COALESCE(P.RDB$NULL_FLAG, F.RDB$NULL_FLAG)
      FROM RDB$PROCEDURE_PARAMETERS P
      JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = P.RDB$FIELD_SOURCE
      WHERE P.RDB$PROCEDURE_NAME = :V_OBJETO
        AND P.RDB$PARAMETER_TYPE = 1
      ORDER BY P.RDB$PARAMETER_NUMBER
      INTO
          :TMPFLD01_CAMPO,
          :TMPFLD01_POSICION,
          :V_FIELD_TYPE,
          :V_FIELD_SUB_TYPE,
          :V_FIELD_LENGTH,
          :V_FIELD_SCALE,
          :V_FIELD_PRECISION,
          :V_NULL_FLAG
    DO
    BEGIN
      ID_TMPFLD01 = ID_TMPFLD01 + 1;
      TMPFLD01_TIPO_OBJETO = V_TIPO_OBJETO;
      TMPFLD01_OBJETO = V_OBJETO;
      TMPFLD01_SECCION = 'SALIDA';
      TMPFLD01_TIPO_DATO = 'UNKNOWN';
      TMPFLD01_LONGITUD = V_FIELD_LENGTH;
      TMPFLD01_ESCALA = V_FIELD_SCALE;
      TMPFLD01_PRECISION = V_FIELD_PRECISION;
      TMPFLD01_REQUERIDO = IIF(V_NULL_FLAG = 1, 'S', 'N');
      TMPFLD01_FAPL = CURRENT_TIMESTAMP;

      IF (V_FIELD_TYPE = 7) THEN TMPFLD01_TIPO_DATO = IIF(V_FIELD_SUB_TYPE = 1, 'NUMERIC', IIF(V_FIELD_SUB_TYPE = 2, 'DECIMAL', 'SMALLINT'));
      IF (V_FIELD_TYPE = 8) THEN TMPFLD01_TIPO_DATO = IIF(V_FIELD_SUB_TYPE = 1, 'NUMERIC', IIF(V_FIELD_SUB_TYPE = 2, 'DECIMAL', 'INTEGER'));
      IF (V_FIELD_TYPE = 10) THEN TMPFLD01_TIPO_DATO = 'FLOAT';
      IF (V_FIELD_TYPE = 12) THEN TMPFLD01_TIPO_DATO = 'DATE';
      IF (V_FIELD_TYPE = 13) THEN TMPFLD01_TIPO_DATO = 'TIME';
      IF (V_FIELD_TYPE = 14) THEN TMPFLD01_TIPO_DATO = 'CHAR';
      IF (V_FIELD_TYPE = 16) THEN TMPFLD01_TIPO_DATO = IIF(V_FIELD_SUB_TYPE = 1, 'NUMERIC', IIF(V_FIELD_SUB_TYPE = 2, 'DECIMAL', 'BIGINT'));
      IF (V_FIELD_TYPE = 27) THEN TMPFLD01_TIPO_DATO = 'DOUBLE PRECISION';
      IF (V_FIELD_TYPE = 35) THEN TMPFLD01_TIPO_DATO = 'TIMESTAMP';
      IF (V_FIELD_TYPE = 37) THEN TMPFLD01_TIPO_DATO = 'VARCHAR';
      IF (V_FIELD_TYPE = 261) THEN TMPFLD01_TIPO_DATO = 'BLOB';

      SUSPEND;
    END
  END
END^

SET TERM ; ^

GRANT EXECUTE ON PROCEDURE SP_PLUGIN_FIELDS TO SMX_ROLE;

COMMIT;
