SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_PLUGIN_DEPENDENCIES (
    P_TIPO_OBJETO VARCHAR(20),
    P_OBJETO VARCHAR(63)
)
RETURNS (
    TMPDICC01_NODE_ID VARCHAR(80),
    TMPDICC01_PARENT_ID VARCHAR(80),
    TMPDICC01_TIPO VARCHAR(20),
    TMPDICC01_NOMBRE VARCHAR(80),
    TMPDICC01_OBJETO VARCHAR(80),
    TMPDICC01_ORDEN INTEGER,
    ID_TMPDICC01 INTEGER,
    TMPDICC01_FAPL TIMESTAMP
)
AS
DECLARE VARIABLE V_TIPO_OBJETO VARCHAR(20);
DECLARE VARIABLE V_OBJETO VARCHAR(63);
DECLARE VARIABLE V_ALIAS VARCHAR(9);
DECLARE VARIABLE V_DEP_NAME VARCHAR(80);
DECLARE VARIABLE V_DEP_TYPE VARCHAR(20);
DECLARE VARIABLE V_PARENT_ID VARCHAR(80);
DECLARE VARIABLE V_OUT_ORDEN INTEGER;
BEGIN
  V_TIPO_OBJETO = UPPER(TRIM(:P_TIPO_OBJETO));
  V_OBJETO = UPPER(TRIM(:P_OBJETO));
  V_ALIAS = SUBSTRING(:V_OBJETO FROM 1 FOR 9);
  ID_TMPDICC01 = 0;

  TMPDICC01_NODE_ID = 'ROOT_TABLES';
  TMPDICC01_PARENT_ID = '';
  TMPDICC01_TIPO = 'TABLE';
  TMPDICC01_NOMBRE = 'Tablas';
  TMPDICC01_OBJETO = '';
  TMPDICC01_ORDEN = 10;
  TMPDICC01_FAPL = CURRENT_TIMESTAMP;
  SUSPEND;

  TMPDICC01_NODE_ID = 'ROOT_VIEWS';
  TMPDICC01_PARENT_ID = '';
  TMPDICC01_TIPO = 'VIEW';
  TMPDICC01_NOMBRE = 'Vistas';
  TMPDICC01_OBJETO = '';
  TMPDICC01_ORDEN = 20;
  TMPDICC01_FAPL = CURRENT_TIMESTAMP;
  SUSPEND;

  TMPDICC01_NODE_ID = 'ROOT_PROCEDURES';
  TMPDICC01_PARENT_ID = '';
  TMPDICC01_TIPO = 'PROCEDURE';
  TMPDICC01_NOMBRE = 'Procedimientos';
  TMPDICC01_OBJETO = '';
  TMPDICC01_ORDEN = 30;
  TMPDICC01_FAPL = CURRENT_TIMESTAMP;
  SUSPEND;

  FOR
    SELECT DISTINCT
        TRIM(DB.TMPPLUGDB01_OBJETO),
        UPPER(TRIM(DB.TMPPLUGDB01_TIPO))
    FROM TMP_PLUGDB01 DB
    JOIN (
      /* Dependencias reales del motor: objetos que usa el objeto seleccionado. */
      SELECT
          TRIM(D.RDB$DEPENDED_ON_NAME) AS OBJETO
      FROM RDB$DEPENDENCIES D
      WHERE TRIM(D.RDB$DEPENDENT_NAME) = :V_OBJETO

      UNION

      /* Impacto directo: objetos que usan al objeto seleccionado. */
      SELECT
          TRIM(D.RDB$DEPENDENT_NAME) AS OBJETO
      FROM RDB$DEPENDENCIES D
      WHERE TRIM(D.RDB$DEPENDED_ON_NAME) = :V_OBJETO

      UNION

      /* Foreign keys salientes: tablas referenciadas por la tabla seleccionada. */
      SELECT
          TRIM(PK.RDB$RELATION_NAME) AS OBJETO
      FROM RDB$RELATION_CONSTRAINTS FK
      JOIN RDB$REF_CONSTRAINTS REF ON REF.RDB$CONSTRAINT_NAME = FK.RDB$CONSTRAINT_NAME
      JOIN RDB$RELATION_CONSTRAINTS PK ON PK.RDB$CONSTRAINT_NAME = REF.RDB$CONST_NAME_UQ
      WHERE FK.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY'
        AND TRIM(FK.RDB$RELATION_NAME) = :V_OBJETO

      UNION

      /* Foreign keys entrantes: tablas que referencian la tabla seleccionada. */
      SELECT
          TRIM(FK.RDB$RELATION_NAME) AS OBJETO
      FROM RDB$RELATION_CONSTRAINTS FK
      JOIN RDB$REF_CONSTRAINTS REF ON REF.RDB$CONSTRAINT_NAME = FK.RDB$CONSTRAINT_NAME
      JOIN RDB$RELATION_CONSTRAINTS PK ON PK.RDB$CONSTRAINT_NAME = REF.RDB$CONST_NAME_UQ
      WHERE FK.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY'
        AND TRIM(PK.RDB$RELATION_NAME) = :V_OBJETO

      UNION

      /*
       * RELA_ salientes usando SP_PLUGIN_FIELDS:
       * el objeto seleccionado declara RELA_ALIAS y se busca el objeto real
       * en SP_PLUGIN_DB por el alias Venture.
       */
      SELECT
          TRIM(DB_REL.TMPPLUGDB01_OBJETO) AS OBJETO
      FROM SP_PLUGIN_FIELDS(:V_TIPO_OBJETO, :V_OBJETO) FLD
      JOIN TMP_PLUGDB01 DB_REL
        ON DB_REL.TMPPLUGDB01_USUARIO = CURRENT_USER
       AND TRIM(DB_REL.TMPPLUGDB01_OBJETO) STARTING WITH SUBSTRING(TRIM(FLD.TMPFLD01_CAMPO) FROM 6 FOR 9)
      WHERE TRIM(FLD.TMPFLD01_CAMPO) STARTING WITH 'RELA_'
        AND NOT (TRIM(FLD.TMPFLD01_CAMPO) STARTING WITH 'RELA_SOCSYST10')
        AND COALESCE(TRIM(DB_REL.TMPPLUGDB01_OBJETO), '') <> ''

      UNION

      /*
       * RELA_SOCSYST10 usando la regla Venture encapsulada en
       * SP_PLUGIN_SOCSYST10.
       */
      SELECT
          TRIM(SS10.TMPSS10_OBJETO) AS OBJETO
      FROM SP_PLUGIN_FIELDS(:V_TIPO_OBJETO, :V_OBJETO) FLD
      JOIN SP_PLUGIN_SOCSYST10(TRIM(FLD.TMPFLD01_CAMPO)) SS10
        ON COALESCE(TRIM(SS10.TMPSS10_OBJETO), '') <> ''
      WHERE TRIM(FLD.TMPFLD01_CAMPO) STARTING WITH 'RELA_SOCSYST10'

      UNION

      /*
       * RELA_ entrantes:
       * objetos que tienen un campo RELA_ALIAS apuntando al alias del objeto
       * seleccionado. Esta parte usa metadata directa porque Firebird 2.5 no
       * permite invocar cómodamente SP_PLUGIN_FIELDS por cada fila del
       * diccionario dentro de un SELECT correlacionado.
       */
      SELECT
          TRIM(RF.RDB$RELATION_NAME) AS OBJETO
      FROM RDB$RELATION_FIELDS RF
      JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = RF.RDB$RELATION_NAME
      WHERE COALESCE(R.RDB$SYSTEM_FLAG, 0) = 0
        AND TRIM(RF.RDB$FIELD_NAME) STARTING WITH 'RELA_' || :V_ALIAS
    ) X ON TRIM(DB.TMPPLUGDB01_OBJETO) = X.OBJETO
    WHERE DB.TMPPLUGDB01_USUARIO = CURRENT_USER
      AND COALESCE(TRIM(DB.TMPPLUGDB01_OBJETO), '') <> ''
      AND TRIM(DB.TMPPLUGDB01_OBJETO) <> :V_OBJETO
      AND (
        UPPER(TRIM(DB.TMPPLUGDB01_TIPO)) IN ('TABLE', 'VIEW', 'PROCEDURE') OR
        UPPER(TRIM(DB.TMPPLUGDB01_TIPO)) IN ('TABLA', 'VISTA', 'PROCEDIMIENTO') OR
        UPPER(TRIM(DB.TMPPLUGDB01_TIPO)) IN ('T', 'V', 'P', 'SP')
      )
    ORDER BY 2, 1
    INTO :V_DEP_NAME, :V_DEP_TYPE
  DO
  BEGIN
    V_PARENT_ID = NULL;
    V_OUT_ORDEN = 0;

    IF ((V_DEP_TYPE = 'TABLE') OR (V_DEP_TYPE = 'TABLA') OR (V_DEP_TYPE = 'T')) THEN
    BEGIN
      V_DEP_TYPE = 'TABLE';
      V_PARENT_ID = 'ROOT_TABLES';
      V_OUT_ORDEN = 11;
    END

    IF ((V_DEP_TYPE = 'VIEW') OR (V_DEP_TYPE = 'VISTA') OR (V_DEP_TYPE = 'V')) THEN
    BEGIN
      V_DEP_TYPE = 'VIEW';
      V_PARENT_ID = 'ROOT_VIEWS';
      V_OUT_ORDEN = 21;
    END

    IF ((V_DEP_TYPE = 'PROCEDURE') OR (V_DEP_TYPE = 'PROCEDIMIENTO') OR (V_DEP_TYPE = 'P') OR (V_DEP_TYPE = 'SP')) THEN
    BEGIN
      V_DEP_TYPE = 'PROCEDURE';
      V_PARENT_ID = 'ROOT_PROCEDURES';
      V_OUT_ORDEN = 31;
    END

    IF (V_PARENT_ID IS NOT NULL) THEN
    BEGIN
      ID_TMPDICC01 = ID_TMPDICC01 + 1;
      TMPDICC01_NODE_ID = V_DEP_TYPE || '_' || V_DEP_NAME;
      TMPDICC01_PARENT_ID = V_PARENT_ID;
      TMPDICC01_TIPO = V_DEP_TYPE;
      TMPDICC01_NOMBRE = V_DEP_NAME;
      TMPDICC01_OBJETO = V_DEP_NAME;
      TMPDICC01_ORDEN = V_OUT_ORDEN;
      TMPDICC01_FAPL = CURRENT_TIMESTAMP;
      SUSPEND;
    END
  END
END^

SET TERM ; ^

GRANT EXECUTE ON PROCEDURE SP_PLUGIN_DEPENDENCIES TO SMX_ROLE;

COMMIT;
