CREATE TABLE TMP_PLUGDB01 (
    ID_TMPPLUGDB01 INTEGER,
    TMPPLUGDB01_NODE_ID VARCHAR(80),
    TMPPLUGDB01_PARENT_ID VARCHAR(80),
    TMPPLUGDB01_TIPO VARCHAR(20),
    TMPPLUGDB01_NOMBRE VARCHAR(80),
    TMPPLUGDB01_OBJETO VARCHAR(80),
    TMPPLUGDB01_ORDEN INTEGER,
    TMPPLUGDB01_FAPL TIMESTAMP,
    TMPPLUGDB01_USUARIO VARCHAR(31)
);

CREATE INDEX IDX_TMP_PLUGDB01_USUARIO ON TMP_PLUGDB01 (TMPPLUGDB01_USUARIO);
CREATE INDEX IDX_TMP_PLUGDB01_OBJETO ON TMP_PLUGDB01 (TMPPLUGDB01_USUARIO, TMPPLUGDB01_OBJETO);
CREATE INDEX IDX_TMP_PLUGDB01_TIPO ON TMP_PLUGDB01 (TMPPLUGDB01_USUARIO, TMPPLUGDB01_TIPO);

/* Permisos de la tabla cache del plugin */
GRANT SELECT, INSERT, UPDATE, DELETE ON TMP_PLUGDB01 TO SMX_ROLE;

COMMIT;
