SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_PLUGIN_SOCSYST10 (
    P_RELA VARCHAR(80)
)
RETURNS (
    TMPSS10_OBJETO VARCHAR(80),
    TMPSS10_TIPO VARCHAR(20),
    TMPSS10_FAPL TIMESTAMP
)
AS
DECLARE VARIABLE V_RELA VARCHAR(80);
DECLARE VARIABLE V_PAYLOAD VARCHAR(80);
DECLARE VARIABLE V_SUFFIX VARCHAR(80);
DECLARE VARIABLE V_CODIGO VARCHAR(5);
DECLARE VARIABLE V_MASK VARCHAR(80);
BEGIN
  V_RELA = UPPER(TRIM(:P_RELA));
  TMPSS10_FAPL = CURRENT_TIMESTAMP;

  IF (NOT (V_RELA STARTING WITH 'RELA_SOCSYST10')) THEN
    EXIT;

  V_PAYLOAD = SUBSTRING(:V_RELA FROM 15);
  V_PAYLOAD = TRIM(:V_PAYLOAD);

  IF ((V_PAYLOAD IS NULL) OR (V_PAYLOAD = '')) THEN
  BEGIN
    FOR
      SELECT FIRST 1
          TRIM(DB.TMPPLUGDB01_OBJETO),
          UPPER(TRIM(DB.TMPPLUGDB01_TIPO))
      FROM TMP_PLUGDB01 DB
      WHERE DB.TMPPLUGDB01_USUARIO = CURRENT_USER
        AND TRIM(DB.TMPPLUGDB01_OBJETO) STARTING WITH 'SOCSYST10'
        AND UPPER(TRIM(DB.TMPPLUGDB01_TIPO)) IN ('TABLE', 'TABLA', 'T')
      ORDER BY TRIM(DB.TMPPLUGDB01_OBJETO)
      INTO :TMPSS10_OBJETO, :TMPSS10_TIPO
    DO
    BEGIN
      TMPSS10_TIPO = 'TABLE';
      SUSPEND;
    END
    EXIT;
  END

  V_SUFFIX = :V_PAYLOAD;
  IF (V_SUFFIX STARTING WITH '_') THEN
    V_SUFFIX = SUBSTRING(:V_SUFFIX FROM 2);

  IF (CHAR_LENGTH(:V_SUFFIX) < 5) THEN
    EXIT;

  V_CODIGO = SUBSTRING(:V_SUFFIX FROM 1 FOR 3) || SUBSTRING(:V_SUFFIX FROM 4 FOR 2);
  V_MASK = 'CBO_SOCSYST10_' || :V_CODIGO;

  FOR
    SELECT DISTINCT
        TRIM(DB.TMPPLUGDB01_OBJETO),
        UPPER(TRIM(DB.TMPPLUGDB01_TIPO))
    FROM TMP_PLUGDB01 DB
    WHERE DB.TMPPLUGDB01_USUARIO = CURRENT_USER
      AND TRIM(DB.TMPPLUGDB01_OBJETO) STARTING WITH :V_MASK
      AND (
        UPPER(TRIM(DB.TMPPLUGDB01_TIPO)) IN ('VIEW', 'VISTA', 'V') OR
        UPPER(TRIM(DB.TMPPLUGDB01_TIPO)) IN ('PROCEDURE', 'PROCEDIMIENTO', 'P', 'SP')
      )
    ORDER BY 2, 1
    INTO :TMPSS10_OBJETO, :TMPSS10_TIPO
  DO
  BEGIN
    IF ((TMPSS10_TIPO = 'VISTA') OR (TMPSS10_TIPO = 'V')) THEN
      TMPSS10_TIPO = 'VIEW';

    IF ((TMPSS10_TIPO = 'PROCEDIMIENTO') OR (TMPSS10_TIPO = 'P') OR (TMPSS10_TIPO = 'SP')) THEN
      TMPSS10_TIPO = 'PROCEDURE';

    SUSPEND;
  END
END^

SET TERM ; ^

GRANT EXECUTE ON PROCEDURE SP_PLUGIN_SOCSYST10 TO SMX_ROLE;

COMMIT;
