SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_PLUGIN_DB_CACHE
RETURNS (
    TMPDICC01_NODE_ID VARCHAR(80),
    TMPDICC01_PARENT_ID VARCHAR(80),
    TMPDICC01_TIPO VARCHAR(20),
    TMPDICC01_NOMBRE VARCHAR(80),
    TMPDICC01_OBJETO VARCHAR(80),
    TMPDICC01_ORDEN INTEGER,
    ID_TMPDICC01 INTEGER,
    TMPDICC01_FAPL TIMESTAMP
)
AS
DECLARE VARIABLE V_ID INTEGER;
BEGIN
  DELETE FROM TMP_PLUGDB01
  WHERE TMPPLUGDB01_USUARIO = CURRENT_USER;

  V_ID = 0;

  V_ID = V_ID + 1;
  TMPDICC01_NODE_ID = 'ROOT_TABLES';
  TMPDICC01_PARENT_ID = '';
  TMPDICC01_TIPO = 'TABLE';
  TMPDICC01_NOMBRE = 'Tablas';
  TMPDICC01_OBJETO = '';
  TMPDICC01_ORDEN = 10;
  ID_TMPDICC01 = :V_ID;
  TMPDICC01_FAPL = CURRENT_TIMESTAMP;

  INSERT INTO TMP_PLUGDB01 (
      ID_TMPPLUGDB01,
      TMPPLUGDB01_NODE_ID,
      TMPPLUGDB01_PARENT_ID,
      TMPPLUGDB01_TIPO,
      TMPPLUGDB01_NOMBRE,
      TMPPLUGDB01_OBJETO,
      TMPPLUGDB01_ORDEN,
      TMPPLUGDB01_FAPL,
        TMPPLUGDB01_USUARIO
    ) VALUES (
      :ID_TMPDICC01,
      :TMPDICC01_NODE_ID,
      :TMPDICC01_PARENT_ID,
      :TMPDICC01_TIPO,
      :TMPDICC01_NOMBRE,
      :TMPDICC01_OBJETO,
      :TMPDICC01_ORDEN,
      CURRENT_TIMESTAMP,
        CURRENT_USER
    );
  SUSPEND;

  V_ID = V_ID + 1;
  TMPDICC01_NODE_ID = 'ROOT_VIEWS';
  TMPDICC01_PARENT_ID = '';
  TMPDICC01_TIPO = 'VIEW';
  TMPDICC01_NOMBRE = 'Vistas';
  TMPDICC01_OBJETO = '';
  TMPDICC01_ORDEN = 20;
  ID_TMPDICC01 = :V_ID;
  TMPDICC01_FAPL = CURRENT_TIMESTAMP;

  INSERT INTO TMP_PLUGDB01 (
      ID_TMPPLUGDB01,
      TMPPLUGDB01_NODE_ID,
      TMPPLUGDB01_PARENT_ID,
      TMPPLUGDB01_TIPO,
      TMPPLUGDB01_NOMBRE,
      TMPPLUGDB01_OBJETO,
      TMPPLUGDB01_ORDEN,
      TMPPLUGDB01_FAPL,
        TMPPLUGDB01_USUARIO
    ) VALUES (
      :ID_TMPDICC01,
      :TMPDICC01_NODE_ID,
      :TMPDICC01_PARENT_ID,
      :TMPDICC01_TIPO,
      :TMPDICC01_NOMBRE,
      :TMPDICC01_OBJETO,
      :TMPDICC01_ORDEN,
      CURRENT_TIMESTAMP,
        CURRENT_USER
    );
  SUSPEND;

  V_ID = V_ID + 1;
  TMPDICC01_NODE_ID = 'ROOT_PROCEDURES';
  TMPDICC01_PARENT_ID = '';
  TMPDICC01_TIPO = 'PROCEDURE';
  TMPDICC01_NOMBRE = 'Procedimientos';
  TMPDICC01_OBJETO = '';
  TMPDICC01_ORDEN = 30;
  ID_TMPDICC01 = :V_ID;
  TMPDICC01_FAPL = CURRENT_TIMESTAMP;

  INSERT INTO TMP_PLUGDB01 (
      ID_TMPPLUGDB01,
      TMPPLUGDB01_NODE_ID,
      TMPPLUGDB01_PARENT_ID,
      TMPPLUGDB01_TIPO,
      TMPPLUGDB01_NOMBRE,
      TMPPLUGDB01_OBJETO,
      TMPPLUGDB01_ORDEN,
      TMPPLUGDB01_FAPL,
        TMPPLUGDB01_USUARIO
    ) VALUES (
      :ID_TMPDICC01,
      :TMPDICC01_NODE_ID,
      :TMPDICC01_PARENT_ID,
      :TMPDICC01_TIPO,
      :TMPDICC01_NOMBRE,
      :TMPDICC01_OBJETO,
      :TMPDICC01_ORDEN,
      CURRENT_TIMESTAMP,
        CURRENT_USER
    );
  SUSPEND;

  FOR
    SELECT
        'TABLE_' || TRIM(R.RDB$RELATION_NAME),
        'ROOT_TABLES',
        'TABLE',
        TRIM(R.RDB$RELATION_NAME),
        TRIM(R.RDB$RELATION_NAME),
        11
    FROM RDB$RELATIONS R
    WHERE COALESCE(R.RDB$SYSTEM_FLAG, 0) = 0
      AND R.RDB$VIEW_BLR IS NULL
    ORDER BY TRIM(R.RDB$RELATION_NAME)
    INTO
        :TMPDICC01_NODE_ID,
        :TMPDICC01_PARENT_ID,
        :TMPDICC01_TIPO,
        :TMPDICC01_NOMBRE,
        :TMPDICC01_OBJETO,
        :TMPDICC01_ORDEN
  DO
  BEGIN
    V_ID = V_ID + 1;
    ID_TMPDICC01 = :V_ID;
    TMPDICC01_FAPL = CURRENT_TIMESTAMP;

    INSERT INTO TMP_PLUGDB01 (
        ID_TMPPLUGDB01,
        TMPPLUGDB01_NODE_ID,
        TMPPLUGDB01_PARENT_ID,
        TMPPLUGDB01_TIPO,
        TMPPLUGDB01_NOMBRE,
        TMPPLUGDB01_OBJETO,
        TMPPLUGDB01_ORDEN,
        TMPPLUGDB01_FAPL,
        TMPPLUGDB01_USUARIO
    ) VALUES (
        :ID_TMPDICC01,
        :TMPDICC01_NODE_ID,
        :TMPDICC01_PARENT_ID,
        :TMPDICC01_TIPO,
        :TMPDICC01_NOMBRE,
        :TMPDICC01_OBJETO,
        :TMPDICC01_ORDEN,
        CURRENT_TIMESTAMP,
        CURRENT_USER
    );

    SUSPEND;
  END

  FOR
    SELECT
        'VIEW_' || TRIM(R.RDB$RELATION_NAME),
        'ROOT_VIEWS',
        'VIEW',
        TRIM(R.RDB$RELATION_NAME),
        TRIM(R.RDB$RELATION_NAME),
        21
    FROM RDB$RELATIONS R
    WHERE COALESCE(R.RDB$SYSTEM_FLAG, 0) = 0
      AND R.RDB$VIEW_BLR IS NOT NULL
    ORDER BY TRIM(R.RDB$RELATION_NAME)
    INTO
        :TMPDICC01_NODE_ID,
        :TMPDICC01_PARENT_ID,
        :TMPDICC01_TIPO,
        :TMPDICC01_NOMBRE,
        :TMPDICC01_OBJETO,
        :TMPDICC01_ORDEN
  DO
  BEGIN
    V_ID = V_ID + 1;
    ID_TMPDICC01 = :V_ID;
    TMPDICC01_FAPL = CURRENT_TIMESTAMP;

    INSERT INTO TMP_PLUGDB01 (
        ID_TMPPLUGDB01,
        TMPPLUGDB01_NODE_ID,
        TMPPLUGDB01_PARENT_ID,
        TMPPLUGDB01_TIPO,
        TMPPLUGDB01_NOMBRE,
        TMPPLUGDB01_OBJETO,
        TMPPLUGDB01_ORDEN,
        TMPPLUGDB01_FAPL,
        TMPPLUGDB01_USUARIO
    ) VALUES (
        :ID_TMPDICC01,
        :TMPDICC01_NODE_ID,
        :TMPDICC01_PARENT_ID,
        :TMPDICC01_TIPO,
        :TMPDICC01_NOMBRE,
        :TMPDICC01_OBJETO,
        :TMPDICC01_ORDEN,
        CURRENT_TIMESTAMP,
        CURRENT_USER
    );

    SUSPEND;
  END

  FOR
    SELECT
        'PROCEDURE_' || TRIM(P.RDB$PROCEDURE_NAME),
        'ROOT_PROCEDURES',
        'PROCEDURE',
        TRIM(P.RDB$PROCEDURE_NAME),
        TRIM(P.RDB$PROCEDURE_NAME),
        31
    FROM RDB$PROCEDURES P
    WHERE COALESCE(P.RDB$SYSTEM_FLAG, 0) = 0
    ORDER BY TRIM(P.RDB$PROCEDURE_NAME)
    INTO
        :TMPDICC01_NODE_ID,
        :TMPDICC01_PARENT_ID,
        :TMPDICC01_TIPO,
        :TMPDICC01_NOMBRE,
        :TMPDICC01_OBJETO,
        :TMPDICC01_ORDEN
  DO
  BEGIN
    V_ID = V_ID + 1;
    ID_TMPDICC01 = :V_ID;
    TMPDICC01_FAPL = CURRENT_TIMESTAMP;

    INSERT INTO TMP_PLUGDB01 (
        ID_TMPPLUGDB01,
        TMPPLUGDB01_NODE_ID,
        TMPPLUGDB01_PARENT_ID,
        TMPPLUGDB01_TIPO,
        TMPPLUGDB01_NOMBRE,
        TMPPLUGDB01_OBJETO,
        TMPPLUGDB01_ORDEN,
        TMPPLUGDB01_FAPL,
        TMPPLUGDB01_USUARIO
    ) VALUES (
        :ID_TMPDICC01,
        :TMPDICC01_NODE_ID,
        :TMPDICC01_PARENT_ID,
        :TMPDICC01_TIPO,
        :TMPDICC01_NOMBRE,
        :TMPDICC01_OBJETO,
        :TMPDICC01_ORDEN,
        CURRENT_TIMESTAMP,
        CURRENT_USER
    );

    SUSPEND;
  END
END^

SET TERM ; ^

GRANT EXECUTE ON PROCEDURE SP_PLUGIN_DB_CACHE TO SMX_ROLE;

COMMIT;
